version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarthome-network
    healthcheck: # <- Добавьте этот блок
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]  # Проверяет готовность к соединениям
      interval: 10s  # Интервал проверки
      timeout: 5s    # Таймаут на проверку
      retries: 5     # Кол-во попыток
      start_period: 30s  # Время на старт перед первой проверк

  temperature-api:
    ports:
      - "8081:8081"
    image: temperature-service:latest
    container_name: smarthome-temperature-api
    networks:
      - smarthome-network

  influxdb:
    image: influxdb:2.7
    container_name: telemetry-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=pass1234
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - smarthome-network

  telemetry-service:
    image: telemetry-service:latest
    container_name: telemetry-service
    ports:
      - "8083:8083"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=telemetry_bucket
    depends_on:
      - influxdb
    networks:
      - smarthome-network

  device-service:
    image: device-service:latest
    container_name: device-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/device_db
    depends_on:
      - postgres
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:
  influxdb-data:
  influxdb-config:

networks:
  smarthome-network:
    driver: bridge